spring:
   profiles:
      active: dev
---
spring:
  config:
    activate:
      on-profile: production
  application:
    name: OnasisTownHouse
  datasource:
      url: jdbc:mysql://192.168.100.90/onasistownhouse
      username: amaeschiffer
      password: ImNumber4#@4
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: none
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: OnasisTownHouse
  datasource:
      url: jdbc:mysql://181.215.79.190:3306/onasistownhouse
      username: amaeschiffer
      password: ImNumber4#@4
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error  
---
spring:
  config:
    activate:
      on-profile: testing
  application:
    name: OnasisTownHouse
  datasource:
      url: jdbc:mysql://localhost:3306/onasistownhouse
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error