spring:
   profiles:
      active: production
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: OnasisTownHouse
  datasource:
      url: jdbc:mysql://181.215.79.190:3306/onasistownhouse
      username: amaeschiffer
      password: ImNumber4#@4
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MariaDB104Dialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 30m
storage: 
  images: C:\\filetemp\\images\\
  videos: C:\\filetemp\\videos\\
  file: ./laporan/
  reports: C:\\Users\\Putri\\JaspersoftWorkspace\\MyReports\\
---
spring:
  config:
    activate:
      on-profile: production
  application:
    name: OnasisTownHouse
  datasource:
      url: jdbc:mysql://181.215.79.190:3306/onasistownhouse
      username: amaeschiffer
      password: ImNumber4#@4
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MariaDB104Dialect
         ddl-auto: none
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
security:
  require-ssl: true
server:
  ssl:
    key-store: /etc/letsencrypt/live/onasistownhouse.com/keystore.p12
    key-store-password: ImNumber4
    keyStoreType: PKCS12
    keyAlias: onasistownhouse
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 30m
storage: 
  images: /home/onasistownhouse.com/storage/images/
  videos: /home/onasistownhouse.com/storage/videos/
  file: /home/onasistownhouse.com/storage/file/
  reports: /home/onasistownhouse.com/storage/reports/
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /home/onasistownhouse.com/logs/onasistownhouse.com.jar_log